#! /bin/bash

E=" Download"
PM=" Back to previous menu"
MM=" Back to main menu"
I=" Quit"
CC="Confirm"
R="Back to main"

## Main Menu Vars
_01=" Install" # Aa
_02=" Update" # Ab
_03=" Tools" # Af
_04=" Tests and Support" # Ag
_05=" Fix" # Ad
_06=" Download"
_07=" Back"
#_0f=" Modifier" # Ac
## menu install
#_1a=" $(echo -e "Depuis une archive locale ")" # A1
_1a=" From a local package" # A2
_1b=" From NVIDIA server" # A3
_1c=" Install Optimus (GIT)" # B6
_1d=" Driver uninstall" # B2
## menu update
_2a=" Build driver only" # G1
_2b=" Build driver for an other kernel" # G2
_2c=" Optimus source update (GIT)" # G3
_2d=" Driver update" # G4
## menu modif 
_3a=" Edit xorg.conf " # G5
_3b=" Edit script config" # G6
_3c=" Nvidia Settings" # G8
_3d=" Manage drivers packages" # G9
_3e=" Compil" # G10
#G7=" Gérer" # G7
## menu manage
_4a=" GLX test" # G15
_4b=" Manual" # G16
_4c=" Change log" # G17
_4d=" About zenvidia " # G18

## menu manage_pcks
G9a="Remove"
G9b="Backup"
G9c="Restore"
G9d="Driver remove"
G9e="Driver backup"
G9f="Remove the associated directory"
G9g="Please confirm :"
G9h="Remove primary driver directory"

## menu test
G20="GLXGears"
G21="GLXSpheres"

## Classic answer
ansOK="OK"
ansNF="NOT PRESENT"
ansNA="NONE"
ansCF="Confirm your choice :"

### NETWORK CONTROL
msg205="Network connection control" # 205

### FIRST START
msg_00_01="DRIVER STUFFER PRO" # 701*
msg_00_02="System :" # 706*
msg_00_04="Card" # 708*
msg_00_06="Repositories are met" # 710
msg_00_07="NVIDIA repository dosn't exist'" # 711*
msg_00_08="Choose a place (prefer /usr/local/)" # 712*

## MAIN MENU
msg_0_00="Processor type :" # 707*
msg_0_01="Driver version installed :" # 202
msg_0_02="Kernel version :" # 202a
msg_0_03="GCC version :" # 202b
msg_0_04="NVIDIA binary version :" # 202c
msg_0_05="Working directories control" # 709*

## MENU INSTALL
msg_1_01="NVIDIA package update fron local dir. " # 603
msg_1_02="Retrieve driver info from NVIDIA server." # 604
msg_1_03="Optimus install from GIT sources" # 617
msg_1_04="Uninstall driver" # 606

## MENU UPDATE
msg_2_01="Build module for current kernel" # 614
msg_2_02="Build module for the selected kernel" # 610
msg_2_03="Optimus update" # 618
msg_2_04="Check driver update list" # 609

## MESSAGE INSTALL
# from directory
m_01_01="Local NVIDIA drivers list :" # 320
m_01_02="Choose one of them or from a local directory:" # 321
m_01_03=" Present version" # 322
m_01_04=" Local directory" # 323
m_01_05="Driver list in" # 324
m_01_06="Select a driver from a local directory" # 325

# check_update
m_01_07="FTP data download" # 206
m_01_08="Compatibility check" # 207
#msg208="n'est pas compatible VDPAU"
#msg209="compatible VDPAU de classe"
m_01_09="is compatible." # 208
m_01_10="compatible" # 209
m_01_11="fit your hadrware " # 210
m_01_12="doesn't fit your hadrware anymore" # 211a

# win_update
m_01_13="What do you want to do?" # 215
m_01_14a="is" # 215c1
m_01_14b="isn't'" # 215c2
m_01_14c="Official and BETA are" # 215c3
m_01_16="in your repository" # 215e
m_01_17="Go back to \"Install\" menu if needed" # 215f
m_01_18="installed" # 215g
m_01_19="Available drivers" # 201
### check available updates
m_01_20a="official"
m_01_20b="BETA"
m_01_20="The $m_01_20a version is :" # 203
m_01_21="The last $m_01_20b is :" # 204

# nv_cmd_uninstall
m_01_22="Old packages removal"

# upgrade_kernel / upgrade_new_kernel
m_02_01="Kernel update" # 612
m_02_02="$m_02_01" # 619
m_02_03="$m_01_13 :" # 601

m_02_04="Driver config" # 607
m_02_05="Optimus service restart" # 608
m_02_06="Done, back to main menu" # 613

m_02_07="Driver install" # 219c
m_02_08="for ha	hardware" # 219d
m_02_09="Pick the kernel to up to date " # 611
# extract_build
m_02_10="Primary package extraction"
m_02_11="Nvidia repository not found"
m_02_12="Extraction failure"
# pre-ops messages
m_02_13="Nvidia Optimus driver install"
m_02_14="Nvidia distro drivers replacement"
m_02_15="Single graphic card install"

# install_dir_sel
m_01_22="Standard (Single GPU)" # 217
m_01_23="Replace distro drivers" # 218
m_01_24="Multi GPU via optimus" # 218b
m_01_25="Install repository choose" # 216
m_01_26="Predefine default repository is"
m_01_27="Multi GPU insall (optimus/bumblebee are present)." # 219a
m_01_28=", optimus/bumblebee is not detected, Install from GIT sources ?'.
(type ENTER to confirm )" # 219
m_01_29="Use Bumblebee"
m_01_30="Use Prime"

msg219b="Driver install in $predifined_dir." 
msg219c="Driver install"
msg219d="for hardware"

# optimus_src_ctrl
m_02_16="Update"
m_02_17="Sources check"
m_02_18="Checking for"
m_02_19="is up to date. Next"
m_02_20="Updating"
# optimus_dependencies_ctrl
m_02_21="Sources and dependencies control"
m_02_22="Some missing dependencies. Install"
m_02_23="Dependencies installed"
m_02_24="Optimus checking"
# build_all
m_02_25="Sources directory is missing. Building"
m_02_26="Optimus and Nvidia GIT sources already installed."
m_02_27="Check for updates instead ?"
m_02_28="Control"
m_02_29="Sources download and install"
m_02_30="Sources compilation and install done"

m_03_01=""

# BUILDING
# bb_build

# bumble_build

# primus_build

# prime_build

# installer_build
m_03_51="$m_02_22"
m_03_52="$m_02_23"
m_03_53="All dependencies are Installed"
# optimus_source_rebuild

# re_build

# install_drv

# download_menu
msg413="Choisissez la version à installer:" # 432
msg413a="officielle"
msg413b="beta"
msg413c="ancienne version"
msg414="téléchargement du pilote officiel" # 439
msg415="téléchargement du pilote BETA" # 447
msg415a="téléchargement du pilote"
msg415b="Erreur de téléchargement\nLa taille du paquet local diffère de l'original.\nRecommencez."
msg415c="Téléchargement du pilote"
msg415d="achever."
msg415e="interrompu"
msg416="$jOoops!$v Pas de nvidia-installer dans mon répertoire.\n Je dois installer un paquet en local" # 416

### dependencies control
msg101="La distribution n'est pas définie. Installez les dépendences du script manuellement " # 97
#msg102="$y INSTALLATION EN COURS..." # 105
#msg103="$y INSTALLATION TERMINÉE..." # 107
### start messages
msg120="$r Le pilote NVIDIA est actuellement chargé."
msg121="$y Il est actuellement utilisé par le système"
msg122="$v Le pilote n'est pas actuellement utilisé par le système.\n Il est donc possible de l'installer en session graphique."
msg123="$v Le pilote NVIDIA n'est pas chargé.\nL'installation peut continuer en mode graphique."
msg121a=" est ne peut être déchargé (sécurité du binaire NVIDIA).\n Vous-devez arrêter la session graphique et relancer$j $(basename $0)$y.\n Lancez la section$j 4$y du menu pour stopper la session graphique."
msg121b=", je tente de le décharger."
msg124="$y Pilote déchargé avec succès."
msg125="$r Je n'ai pas pu déchargerle pilote\n l'installation ne pourra pas avoir lieu."

msg106=" Aucune connexion internet détectée.\n Dans le cas d'un control de mise à jour,\n une connexion valide est obligatoire." # 133
msg_0_06="Connexion réseau " # 111

# Internet connection control function.
msg116="valide"
msg117="non valide."
msg118="sur"
### check available updates
msg212="officiel"
msg213="BETA"





msg211b="$v.\n Passez ou restez à une version antérieure" # 211b
msg211="$msg211a$msg211b" # 211


msg215a="La version installée ("
msg215b=") est déjà la dernière mise à jour.\nRien à faire."





msg301="Démarrage de l'installation..." # 311
msg302="Félicitation! Votre pilotes est installé." # 313
msg303="Copie de sauvegarde du pilote" # 321
msg304="Je peux procéder à l'archivage." # 321
msg305="avec succès" # 324
msg306="sans succès." # 324
msg307="Le script a besoin de cette sauvegarde pour l'archivage\n et d'autre opération. Faites le maunellement\n et demandez à l'auteur d'arranger çà." # 325

msg309="Enfoncer un touche pour continuer." # 328
msg310="Aïe!$v Vous n'avez pas de paquet NVIDIA valide dans votre répertoire \n JE vous suggère d'aller sur le site NVIDIA," # 334
msg311="ici :" # 335
msg312="puis revenez me voir!." # 337
msg313="Retour au menu principal ou redémarrage du serveur X ?" # 338
msg314="Menu Principale." # 339
msg315="Redémarrer X." # 339
msg316="ou sur le dépot ftp NVIDIA"
# f2

msg326="Utilez [TAB] et suivez le chemin jusqu'à votre pilote :" # 326
### UPDATE FUNCTION, FROM INTERNET.
# download functions
msg401="SOYEZ PATIENT!" # 396
msg402="TÉLÉCHARGEMENT TERMINÉ." # 398
msg405="Contrôle du contenu distant..."
msg406="Le paquet signifié"
msg407="n'existe pas"
msg408="liste les paquets de"
msg409="à la place"
msg410="TÉLÉCHARGEMENT"
# script
msg412="Tapez $j[C]$v l'une de ces versions." # 429


msg417=" Connectez moi et redémarrez le script."
msg419="Autre"
msg420="Choisissez un pilote dans la liste"
msg421="Votre choix est :"
msg422="ou un plus ancien dans le menu suivant."
msg423="Sinon, tapez $j[M]$v pour retourner au menu principal."
### ARCHIVING.
# sub function method
msg509="Sélectionnez $j$G$v dans le menu principal." # 500
### UNINSTALL fUnction
msg531="DÉ-INSTALLATION EN COURS!" # 604
msg532="fait, retour au menu principal." # 606
### MAIN MENU





## VOCABULARY
w_01="Téléchargements"
w_02="Téléchargement"


 




