## zenvidia git
# zenvidia gitlab
# zenvidia_git=https://gitlab.com/wildtruc/zenvidia.git
# zenvidia github
zenvidia_git="https://github.com/wildtruc/zenvidia.git"
## nvidia main download site
nvidia_base_url="download.nvidia.com"
## nvidia linux ftp url
nvidia_ftp="download.nvidia.com/XFree86/Linux"
## cuda main html site
cuda_base_url="developer.download.nvidia.com"
## git source name
git_source=origin/master
## Is dependencies resolved: yes (1), no (0)
resolve_dep=0
