#!/bin/bash

#  Zen_notify
#  mar. oct. 11 16:21:02 CEST 2016 (initial prequel)
#  Copyright  2022-2026  PirateProd
#  <wildtruc@noneltd.net>
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with main.c;if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA
set -euo pipefail

# export PS4='->$(tput setaf 6)${LINENO}$(tput sgr 0)$(printf "\\t")-> '
## basics
local_nvdir=/home/$USER/.zenvidia
nvdir=/usr/local/share/zenvidia
script_conf=$nvdir/script.conf
basic_conf=$local_nvdir/basic.conf
# nvtmp=$local_nvdir/notify
zen_docs=/usr/local/share/doc
# deficon=swiss_knife
deficon=zen-emblem
## check if zen_taskbar_menu exit
zen_bar=$(command -v zen_task_menu)

export PATH=$PATH:/usr/local/bin
export TEXTDOMAIN=zenvidia
export TEXTDOMAINDIR=$nvdir/locale

[ $script_conf ] || exit 0
. $script_conf
. $basic_conf
## script could need to sleep during the desktop session boot time.
## to uncomment only in case of session autostart notif issue.
# sleep 15

ARCH=$HOSTTYPE
local_src=$local_nvdir/src
[ -d $local_src ] || mkdir -p $local_src
ifs=$IFS
## capture for exit status
trap "IFS=\$ifs" EXIT

git_hub_api="https://api.github.com/repos/wildtruc/zenvidia/commits?sha=master&per_page=1"
git_lab_api="https://gitlab.com/api/v4/projects/56148921/repository/commits?sha=master&per_page=1"
## gitlhub check (0), gitlab check (1)
# git_master=0
declare -a driver_notif=()
declare driver_up=0 zen_up=0 git_master=0 msg_suffix=$"update"

connected(){
	local site=${site:-$nvidia_base_url}
	ping -c2 ${site} &>/dev/null && echo 0 || echo "$?"
}
version_array(){
	# synt : version_array [object]
	local version=${1}
		local count_array c part prefix='' suffix='' local IFS=' '
		count_array=( $(echo "$version"|tr . ' ') )
		for c in ${count_array[@]}; do
			(( ${#c} < 3 )) && prefix=0 || prefix=''
			part+=$(printf ${prefix}$c)
		done
		[ ${#count_array[@]} -eq 3 ] || suffix='000'
		echo "${part[*]}$suffix"
	return
}
xq_x_query(){
	local cmd="${1}" query="${2}" regex="${3}" reg_type="${4}"
	shift
	local -a cmd_line=() reg_cmd=()
	[ ${reg_type} = 1 ] && reg_cmd=( '|' 'grep' '-Ec' "${regex}") || true
	[ ${reg_type} = 2 ] && reg_cmd=( '|' 'tr' "'\n'" "' '") || true
	cmd_line=( "${cmd}" '|' 'xq' '-x' "${query}" "${reg_cmd[*]}" )
	eval ${cmd_line[*]}
}
git_local_version(){ [ -f ${local_nvdir}/zen_version ] && cat ${local_nvdir}/zen_version || cat ${nvdir}/zen_version; }
git_log_message(){
	git_master=0
	if [ ${git_master} = 0 ]; then
		curl -s "$git_hub_api" | jq -r '.[].commit.message'
	else
		curl -s "$git_hub_api" | jq -r '.[].message'
	fi
}
driver_ctrl(){
	## reset all value.
	local last_array=() DRV_LIST=() # ver_array=()
	local drv_diff=0 greater=0 rem_diff=0 version=0
	local prefix='' suffix='' msg_suffix=''
	local LAST_OFFI=0 LAST_BETA=0 LAST_DRV=''

	if [ $(connected) -eq 0 ]; then
		remote_page=https://${nvidia_ftp}-${ARCH}
		scrap_cmd=("curl" "-s" "$remote_page")
		page='latest.txt'
		index='index.html'
		LAST_OFFI=$(eval ${scrap_cmd[*]}/$page| awk '{print $1}' || echo "none" )
		LAST_BETA=$(eval ${scrap_cmd[*]}/$index | xq -q 'li>span[class="dir"]'| sed -En 's/^(.*)\/$/\1/;$p' || echo "none" )
		# LAST_BETA="565.77" # TEST
		[ -f $local_nvdir/taskbar_message ] && echo '' > $local_nvdir/taskbar_message

		if [ -s $nvdir/version.txt ]; then
			version=$(cat $nvdir/version.txt || true)
		else
			version=$(modinfo -F version nvidia || true)
		fi
		if (( $(version_array "$LAST_BETA") != $(version_array "$LAST_OFFI") )); then
			rem_diff=1 ; last_array=( $(version_array "$LAST_BETA") )
			LAST_DRV=$LAST_BETA
		else
			rem_diff=0 ; last_array=( $(version_array "$LAST_OFFI") )
			LAST_DRV=$LAST_OFFI
		fi
		for last in ${last_array[@]}; do
			(( ${last} == $(version_array "$version") )) || drv_diff=1
			(( ${last} > $(version_array "$version") )) && greater=1
		done
		if [ $rem_diff -eq 1 ]; then
			DRV_LIST=( $"$LAST_OFFI, official driver" $"$LAST_BETA, beta driver" )
		else
			DRV_LIST=( $"$LAST_OFFI, official drivers" )
		fi
		if [ ${#DRV_LIST[@]} -gt 0 ]; then
			local IFS=$'\n'
			cnt=0
			for drv_line in ${DRV_LIST[@]}; do
				driver=$(printf "$drv_line"|cut -d',' -f1)
				release=$(printf "$drv_line"|cut -d',' -f2)
				local sol='' eol=''
				if [ $drv_diff -gt 0 ]; then
					(( ${cnt} > 0 )) && sol='\n' || true
					driver_notif+=( $"$sol<b>$driver</b> $release.$eol" )
					cnt=$((cnt+1))
				fi
			done
			# catch new driver features
			if [[ -n $LAST_DRV ]]; then
				local -a local_readme=() remote_readme=() local_chapter=() remote_chapter=()
				local local_count rem_count chapter_diff chapter_name
				local_readme=( "cat" "${zen_docs}/NVIDIA_GLX-1.0/html/index.html" )
				remote_readme=( "curl" "-s" "https://${nvidia_ftp}-$ARCH/${LAST_DRV}/README/index.html" )
				local_count=$(xq_x_query "${local_readme[*]}" '//dt/span[@class=\"chapter\"]/a' "^[0-9]+\." 1)
				rem_count=$(xq_x_query "${remote_readme[*]}" '//dt/span[@class=\"chapter\"]/a' "^[0-9]+\." 1)
				if (( ${local_count} < ${rem_count} )); then
					echo "${local_count} differ"
					local_chapter=( $(xq_x_query "${local_readme[*]}" '//dt/span[@class=\"chapter\"]/a/attribute::*' '' 0 ) )
					remote_chapter=( $(xq_x_query "${remote_readme[*]}" '//dt/span[@class=\"chapter\"]/a/attribute::*' '' 0 ) )
					chapter_diff=$( echo ${local_chapter[*]} ${remote_chapter[*]} | tr ' ' '\n' | sort | uniq -u)
					chapter_name="$( xq_x_query "${remote_readme[*]}" '//dt/span[@class=\"chapter\"]/a[@href=\"'${chapter_diff}'\"]' '' 2)"
					# chapter_name="$(xq_x_query "${local_readme[*]}" '//dt/span[@class=\"chapter\"]/a[@href=\"'${chapter_diff}'\"]' '' 2)" # TEST
					driver_notif+=( "\n\n<b>"$"Driver major change"":</b>" )
					driver_notif+=( "\n"$"New feature added to Nvidia Readme." )
					driver_notif+=( "\n"$"Open"" <b>"$"Next ${LAST_DRV} major change""</b> "$"from system tray menu" )
					driver_notif+=( "\n"$"and see Chapter"": <b>${chapter_name}</b>"$"for more informations"".\n" )
					echo -e "next_driver=\"${LAST_DRV}\"" > $local_nvdir/taskbar_message
					echo -e "next_change=\"https://${nvidia_ftp}-$ARCH/${LAST_DRV}/README/${chapter_diff}\"" >> $local_nvdir/taskbar_message
					# echo -e "next_change=\"https://${nvidia_ftp}-$ARCH/${LAST_BETA}/README/${chapter_diff}\"" >> $local_nvdir/taskbar_message # TEST
				fi
			fi
			if [[ $greater -gt 0 || ! "$(echo -e "${DRV_LIST[*]}")" =~ $(modinfo -F version nvidia) ]]; then
				notif_msg+=$"Nvidia driver "
				driver_up=1
			fi
		fi
	else
		notif_msg=$"Nvidia driver notification"
		driver_notif+=$"<b>WARNING</b> : No Signal"
		msg_suffix=''
	fi
}
source_ctrl(){
	if [ $(connected) -eq 0 ]; then
		# tmp_git_src=$(mktemp -d $notif_temp/tmp_git.XXX)
		test -f $local_src/zen_git.log || touch $local_src/zen_git.log
		# git_lab_api="https://gitlab.com/api/v4/projects/56148921/repository/commits?sha=master&per_page=1"
		if [ $driver_up -gt 0 ]; then
			notif_txt=$"and Zenvidia"; line='\n'
		else
			notif_txt='Zenvidia'; line=''
		fi
		if [ ${git_master} = 0 ]; then
			git_remote_version=$(curl -s "$git_hub_api" | jq -r '.[].commit.message'| sed -n '1p')
			git_remote_date=$(curl -s "$git_hub_api" | jq -r '.[].commit.committer.date'| awk -F"T" '{print $1}')
			# git_pull_date=$(date -d "@$git_remote_date" +%Y''%m''%d)
		else
			git_remote_version=$(curl -s "$git_lab_api" | jq -r '.[].title')
			git_remote_date=$(curl -s "$git_lab_api" | jq -r '.[].date'| awk -F"T" '{print $1}')
			# git_pull_date=$(date -d "@$git_remote_date" +%Y''%m''%d)
		fi
		if [[ $(git_local_version) != ${git_remote_version} ]]; then
			if (( $(grep -c "${git_remote_version}" $local_src/zen_git.log) == 0 )); then
				git_log_tee="$(cat <<-LOG
					$git_remote_date - $(git_log_message)
				LOG
				)"
				echo -e "* $git_log_tee" | tee -a $local_src/zen_git.log
			fi
			echo -e "zen_new_version=${git_remote_version}" | tee -a $local_nvdir/taskbar_message
			notif_msg+="$notif_txt "
			driver_notif+=($"${line}zenvidia git repo update.""\n""$git_remote_date $git_remote_version")
			zen_up=1
		else
			echo -e "zen_new_version=''" | tee -a $local_nvdir/taskbar_message
			zen_up=0
		fi
	fi
}
notifying(){
	# only display notif if driver_ctrl or source_ctrl are true.
	test -f $local_nvdir/taskbar_message || touch $local_nvdir/taskbar_message
	notif_set=0
	if (( $(connected) == 0 ))&&(( ${driver_up} > 0 || ${zen_up} > 0 )); then
		notif_set=1
		notify-send -t 5000 -u low -i "$deficon" $"${notif_msg[*]}$msg_suffix" "$(echo "${driver_notif[@]}")"
		echo -e "notif=${notif_set}" | tee -a $local_nvdir/taskbar_message
		echo -e "notif_text=\"${driver_notif[@]}\"" | tee -a $local_nvdir/taskbar_message
	fi
	## launch zen_taskbar.
	if [ -e $zen_bar ]; then
		exec $zen_bar &
	fi
}
usage_help(){
	printf "# Usage : zen_notify [option], where option are:\n"
	printf "\t -z : check nvidia & zenvidia.\n"
	printf "\t -n : check nvidia only.\n"
	printf "\t -h : this help.\n"
}
test $# -gt 0 || usage_help
while [ $# -gt 0 ]
	getopts "z n h" OPT; do
	case $OPT in
		z) driver_ctrl; source_ctrl; notifying ;;
		n) driver_ctrl; notifying ;;
		h) usage_help ;;
	esac
done
