#!/bin/bash

# set -euo pipefail
set -uo pipefail
#export PS4='->$(tput setaf 6)${LINENO}$(tput sgr 0)$(printf "\\t")-> '

if [ -e /var/run/nv-modules-reload.pid ]; then
	PCI_ID=$(lspci -mnn | grep "VGA.*NVIDIA" | awk '{print "0000:"$1}')
	DEVICE_DIR="/sys/bus/pci/devices/$PCI_ID"
	d_nv_persistenced=$(command -v nvidia-persistenced)
	d_probe=$(command -v modprobe)
	d_sys=$(command -v systemctl)
	install_dir=/usr/local
	nv_persist_ctl=/etc/systemd/system/multi-user.target.wants/nvidia-persistenced.service

	export PATH=$PATH:$install_dir/bin

	echo "[zenvidia] session modules reload active > exec system daemon service." >&2
	[ -e $nv_persist_ctl ] && $d_sys stop nvidia-persistenced.service && echo "[zenvidia] shuting down nvidia-persistenced" >&2
	if [ $(lsmod | grep -c "nouveau") -gt 0 ]; then
		$d_probe -r nouveau && echo "[zenvidia] unloaded nouveau drivers" >&2 || true
	else
		$d_probe -r -a nvidia_uvm nvidia_drm nvidia_modeset nvidia && echo "[zenvidia] $PCI_ID nvidia modules unload done" >&2 || true
		# echo "[zenvidia] unloaded nvidia drivers rc=$?" >&2
	fi
	if [ -e "/sys/bus/pci/rescan" ]; then
	 	echo 1 > /sys/bus/pci/rescan && echo "[zenvidia] global pci rescan done" >&2 || true
	fi
	$d_probe -a nvidia_uvm nvidia_drm nvidia_modeset nvidia && echo "[zenvidia] $PCI_ID nvidia modules reload done" >&2 || true
	udevadm settle && echo "[zenvidia] $PCI_ID nvidia modules udev settle done" >&2 || true
	command -v restorecon &>/dev/null && restorecon "/boot/symvers-$(uname -r).*" && echo "[zenvidia] $PCI_ID nvidia modules symvers reconnected" >&2 || true
	# if [ -f /lib/systemd/system/systemd-modules-load.service ]; then
	# 	$d_sys restart systemd-modules-load.service
	# fi
	if [ -e $nv_persist_ctl ]; then
		# case: prime offload activated
		systemctl start nvidia-persistenced.service && echo "[zenvidia] Starting nvidia-persistenced" >&2
		$d_sys daemon-reload && echo "[zenvidia] session modules reload active > exec system daemon service." >&2
	fi
	rm -f /var/run/nv-modules-reload.pid
else
	echo "[zenvidia] session modules reload inactive > Nothing to do." >&2
fi
